services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - app-net

  backend:
    build:
      context: ./backend.api
    ports:
      - "5090:443"
      - "5080:80"
    env_file:
      - ./backend.api/.env.backend
    depends_on:
      - postgres
    networks:
      - app-net

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - app-net

volumes:
  pgdata:

networks:
  app-net:
